### ISSUE TITLE
Support for webpack 4

### ISSUE THREAD

**Issue by pavelloz** [m8ms/dynamic-public-path-webpack-plugin#3]
Hey,

I just read https://github.com/m8ms/dynamic-public-path-webpack-plugin/issues/2#issuecomment-315310463

and i was wondering, can you look if the plugin works in webpack 4?

Im trying to make it work, placeholder is present in the bundle, but chunks are not loaded using the variable i provide in global scope.

Do you have any hints on how to debug if the plugin is working or if i misconfigured it?

**Comment by m8ms** [comment]
Hi! I have good news and bad news:
* The good news is Webpack 4 doesn't need this plugin, as it gives public path out of the box. See: https://webpack.js.org/concepts/output/#advanced
* The bad news is Webpack 4 doesn't need this plugin. Therefore I won't be fixing it. If you are migrating to Webpack 4, you will need to set up your app the Webpack way and get rid of my plugin.

Thanks for using anyways :)

**Comment by pavelloz** [comment]
Yeah, ive seen that it is exposed, but ultimately it is so ugly that i would prefer using the plugin. 

What do i mean by ugly?

1) I need to pull cdn path from backend and set it somewhere in variable in html (ie. ASSET_PATH)
2) Then i need the js file that is parsed by webpack to assign it to webpack variable ( ___webpack___ = ASSET_PATH)
3) Then i need to include it before every imports, which makes me add this `public-path.js` to all the entries in webpack config which is very annyoing (this is the solution recommended by sokra in one of the issues on github)

This is ugly and convoluted enough for me to try to use `webpack-require-from` or `dynamic-public-path` - im trying to care about future maintainers and i predict troubles with the no-plugin approach, its much easier to understand where plugin gets the data and where it puts it.

**Comment by m8ms** [comment]
Funny... the way you've given above is exactly how we use this plugin ourselves... except for point 3. Instead I created a whole 'window.appGlobals' namespace (in HTML head) to keep all the ugly hacks in. Including the urls comming from backend at render-time. I put this 'appGlobas' in all relevant tools' exceptions and just use it as a global (very reluctantly).

That's exactly what `__webpack_public_path__` allows you to do as far as I understand (didn't try it!).
My understanding is that you you use the plugin exactly the way I described it in the README, and put a direct reference to a path in `window.myCdn`, right?

In that case I might have to fix the plugin... I wouldn't expect it to be fixed sooner than in two weeks I'm affraid :(

**Comment by pavelloz** [comment]
Yes, using the plugin allows us to remove the 3rd point and this is why i want to use it - without plugin its required to include assignment in every entry point `webpack_public_path` = ASSET_PATH from html :)

1) Yes, in html I'm assigning basically `window.__cdnUrl = "https://my.cdn.com/assets";`
2) in methodName i would put `window.__cdnUrl` (i hope underscores are not a problem),
3) in chunks i would put chunk name where i load stuff - `common`
4) in publicPath i put `publicPathPlaceholder` - effect is that `publicPathPlaceholder` is hardcoded in front of every path (ie. to css/fonts/chunks) but never replaced. From the README i assumed it should be replaced in the browser when webpack tries to use publicPath - is this the correct behavior? Or should it replace it somewhere during the build time?

Also one question, can i pass an array to `chunkName`? From the error ive got in the CLI i understand that it has to be pointer to an entry point that im using, but i have two - two instances in that case seems like an ugly solution :)

**Comment by pavelloz** [comment]
Okay, after reading the source i think i got it.

1) The `placeholder` is used by webpack while trying to resolve paths
2) Plugin replace the placeholder (original publicPath string) with reference to the global variable i defined

I still don't understand whats the purpose of `chunkName`, but at least i know that it should replace my placeholder string with the `methodName` i passed in the plugin during the build time - so i think i misconfigured something at the end of the day :)

**Comment by m8ms** [comment]
When it comes to multiple chunks - I gave the "multiple instance" solution because it came out of the box. To be honest, we use the plugin only on one chunk, which is "webpack.js" (or "manifest" if you like), this is the only chunk that contains absolute paths to CDNs. All other paths are relative in our app, I'd recommend doing the same.

**Comment by pavelloz** [comment]
I think if you have multiple entry points you will endup with multiple webpack runtime chunks (and i think manifest is a part of runtime, but didnt check) - one in each of them. I might be wrong but thats how i understood what happened when i enabled `runtime: true` in new webpacks code splitting settings - it created runtime for every emitted entrypoint.
